name: Build Android

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-android:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4.6.0
      with:
        python-version: '3.9'
    - name: Show myself
      run: uname -a
    - name: Prepare NDK package
      run: wget https://dl.google.com/android/repository/android-ndk-r23c-linux.zip
    - name: Unzip NDK package
      run: unzip -q android-ndk-r23c-linux.zip
    - name: Rename NDK dir
      run: mv android-ndk-r23c ndk
    - name: Clean cache
      run: rm android-ndk-r23c-linux.zip
    - name: Grant permissions
      run: chmod +x android-configure && chmod +x configure
    - name: Build with Android NDK
      run: ./android-configure ndk arm64 21 && make -j8
